//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniPension.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Branch
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Branch()
        {
            this.AppUsers = new HashSet<AppUser>();
        }
    
        public int id { get; set; }
        public string branch_code { get; set; }
        public string branch_name { get; set; }
        public string region { get; set; }
        public string division { get; set; }
        public string BBCode { get; set; }
        public string routingNo { get; set; }
        public string Address { get; set; }
        public string emailAddress { get; set; }
        public string PhoneNo { get; set; }
        public string thana { get; set; }
        public string City { get; set; }
        public string Status { get; set; }
        public string ISO { get; set; }
        public string ZIP { get; set; }
        public string OfficeType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AppUser> AppUsers { get; set; }
    }
}
