//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniPension.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PensionPaymentRequest
    {
        public int Id { get; set; }
        public string PensionerID { get; set; }
        public string PensionerName { get; set; }
        public string PhoneNo { get; set; }
        public string Email { get; set; }
        public string PayIntervalType { get; set; }
        public string PensionerNid { get; set; }
        public string TransactionId { get; set; }
        public Nullable<int> PayingInstallCount { get; set; }
        public Nullable<decimal> PayingAmount { get; set; }
        public Nullable<decimal> CommissionAmount { get; set; }
        public Nullable<decimal> VATAmount { get; set; }
        public string PayMode { get; set; }
        public string CreditAccount { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ApprovedOn { get; set; }
        public string ApprovedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public string NextDueDate { get; set; }
        public string IsSuccess { get; set; }
        public Nullable<System.DateTime> TransactionDateTime { get; set; }
        public string BranchCode { get; set; }
        public string PaymentRefNo { get; set; }
        public Nullable<int> InstallPaidCount { get; set; }
        public Nullable<decimal> InstallPaidAmount { get; set; }
        public string IsCbsDeposited { get; set; }
        public string CBSBatchNo { get; set; }
        public string CBSTraceNo { get; set; }
        public Nullable<System.DateTime> CBSDepositDate { get; set; }
        public string CallBackSuccess { get; set; }
        public Nullable<System.DateTime> LastCallBackTime { get; set; }
    }
}
