//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniPension.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoleMenuMapping
    {
        public int id { get; set; }
        public int appRoleID { get; set; }
        public int subMenuID { get; set; }
        public string isActive { get; set; }
    
        public virtual AppRole AppRole { get; set; }
        public virtual SubMenu SubMenu { get; set; }
    }
}
